import { Palette } from "./types";

const palette: Palette = {
  amazon: {
    colors: ["#FF9900", "#000000"],
    keywords: ["amazon", "aws", "e-commerce"],
    name: "Amazon",
    id: "amazon",
  },
  amd: {
    colors: ["#EF0707", "#BD0000", "#FF2424", "#CA0505", "#FC0C0C"],
    keywords: ["amd", "processor", "graphics"],
    name: "AMD",
    id: "amd",
  },
  apple: {
    colors: ["#781714", "#EB4135", "#FEAD6A", "#FEF695", "#668014"],
    keywords: ["apple", "fruit", "apple fruit"],
    name: "Apple Fruit",
    id: "apple",
  },
  asus: {
    colors: ["#00539B", "#FFFFFF"],
    keywords: ["asus", "asus laptops"],
    name: "ASUS",
    id: "asus",
  },
  avocado: {
    colors: ["#4A7337", "#6B8C21", "#DDD48F", "#CDA989", "#704012"],
    keywords: ["avocado", "fruit", "avocado fruit"],
    name: "Avocado",
    id: "avocado",
  },
  banana: {
    colors: ["#FFFBC9", "#6B3E26", "#FBEC5D"],
    keywords: ["banana", "fruit", "banana fruit"],
    name: "Banana",
    id: "banana",
  },
  beach: {
    colors: ["#1A748E", "#55C2D6", "#F0DF99", "#D38E31", "#992915"],
    keywords: ["beach", "sea", "seashore", "ocean"],
    name: "Beach",
    id: "beach",
  },
  birch: {
    colors: ["#E3B581", "#F1C197", "#EFD0B5", "#F6DEC0", "#FFEBD0"],
    keywords: ["birch", "wood", "tree"],
    name: "Birch Wood",
    id: "birch",
  },
  blackberry: {
    colors: ["#1E212E", "#261923", "#692536", "#EEF7FB", "#C8E2F0"],
    keywords: ["blackberry", "fruit", "blackberry fruit"],
    name: "Blackberry",
    id: "blackberry",
  },
  cherry: {
    colors: ["#79011C", "#B6203B", "#FF0126", "#FBAAB9"],
    keywords: ["cherry", "fruit", "cherry fruit"],
    name: "Cherry",
    id: "cherry",
  },
  coconut: {
    colors: ["#4D331D", "#74533C", "#C59D7D", "#D0D0D8", "#EFEDF6"],
    keywords: ["coconut", "fruit", "coconut fruit"],
    name: "Coconut",
    id: "coconut",
  },
  dell: {
    colors: ["#007DB8", "#EFEFEF", "#FFFFFF", "#454545"],
    keywords: ["dell", "dell computers "],
    name: "dell",
    id: "dell",
  },
  ebay: {
    colors: ["#E53238", "#0064D3", "#F5AF02", "#86B817"],
    keywords: ["ebay", "e bay", "e-commerce"],
    name: "EBay",
    id: "ebay",
  },
  espressowood: {
    colors: ["#231814", "#2D201B", "#432D25", "#35241B"],
    keywords: ["espresso", "wood", "tree"],
    name: "Espresso Wood",
    id: "espressowood",
  },
  facebook: {
    colors: ["#3A5795", "#637BAD", "#ADB9D3", "#EDF0F5", "#333333"],
    keywords: ["facebook", "face book", "social network"],
    name: "Facebook",
    id: "facebook",
  },
  fire: {
    colors: ["#fdcf58", "#757676", "#f27d0c", "#800909", "#f07f13"],
    keywords: ["fire", "agni", "flame", "burn"],
    name: "Fire",
    id: "fire",
  },
  firefox: {
    colors: ["#58BEEC", "#074784", "#FFE513", "#EE8424", "#D65126"],
    keywords: ["firefox", "browser", "mozilla", "mozilla firefox"],
    name: "Firefox",
    id: "firefox",
  },
  flipkart: {
    colors: ["#F7A200", "#F8E831", "#047BD5"],
    keywords: ["flipkart", "flip kart", "e-commerce"],
    name: "Flipkart",
    id: "flipkart",
  },
  github: {
    colors: ["#333333", "#f5f5f5", "#4078c0"],
    keywords: ["github", "git", "git hub"],
    name: "GitHub",
    id: "github",
  },
  google: {
    colors: ["#008744", "#0057e7", "#d62d20", "#ffffff", "#ffa700"],
    keywords: ["google", "google chrome", "browser", "web browser"],
    name: "Google",
    id: "google",
  },
  gooseberry: {
    colors: ["#DADFD0", "#7A8C66", "#778C0C", "#8E8158", "#848469"],
    keywords: ["gooseberry", "fruit", "gooseberry fruit"],
    name: "Gooseberry",
    id: "gooseberry",
  },
  grape: {
    colors: ["#89B061", "#8AB162", "#D9E8BF", "#EDEECE", "#C1DFC3"],
    keywords: ["grape", "vine", "grapevine", "fruit", "grape fruit"],
    name: "Grape",
    id: "grape",
  },
  grape2: {
    colors: ["#BBC0E7", "#B89BE0", "#6546A7", "#571247", "#B477BA"],
    keywords: ["grape", "vine", "grapevine", "fruit", "grape fruit"],
    name: "Grape",
    id: "grape2",
  },
  guava: {
    colors: ["#2D2D2F", "#B0BC7C", "#618229", "#D6DD8F", "#F3B0A7"],
    keywords: ["guava", "fruit", "guava fruit"],
    name: "Guava",
    id: "guava",
  },
  icecream: {
    colors: ["#6b3e26", "#ffc5d9", "#c2f2d0", "#fdf5c9", "#ffcb85"],
    keywords: ["ice cream", "icecream"],
    name: "Ice Cream",
    id: "icecream",
  },
  instagram: {
    colors: ["#F44747", "#EEDC31", "#7FDB6A", "#0E68CE"],
    keywords: ["instagram", "facebook", "social network"],
    name: "Instagram",
    id: "instagram",
  },
  iphone: {
    colors: ["#BDB08A", "#7C7C7C", "#313131", "#F2F1F2", "#A7A7A7"],
    keywords: ["iphone", "i phone", "apple phone", "apple iphone"],
    name: "iPhone",
    id: "iphone",
  },
  ironman: {
    colors: ["#771414", "#beba46", "#8bd3fb", "#bcb841", "#790d0d"],
    keywords: [
      "iron man",
      "ironman",
      "tony stark",
      "robert downy jr",
      "marvel",
      "avengers",
    ],
    name: "Iron Man",
    id: "ironman",
  },
  kiwi: {
    colors: ["#120D0E", "#384D0E", "#82A546", "#D0E3A0", "#A48950", "#F7FBED"],
    keywords: ["kiwi", "kiwifruit", "fruit", "kiwi fruit"],
    name: "Kiwi",
    id: "kiwi",
  },
  lemon: {
    colors: ["#D19402", "#FFDF30", "#FFEAA4", "#80A300", "#2D3F01"],
    keywords: ["lemon", "lime", "fruit", "lemon fruit"],
    name: "Lemon",
    id: "lemon",
  },
  mango: {
    colors: ["#FFCC22", "#FFD93A", "#FFEA47", "#FF8242"],
    keywords: ["mango", "fruit", "mango fruit"],
    name: "Mango",
    id: "mango",
  },
  maple: {
    colors: ["#F1C38E", "#E7B983"],
    keywords: ["maple", "maple wood", "wood", "tree"],
    name: "Maple Wood",
    id: "maple",
  },
  mickeymouse: {
    colors: ["#f9d70b", "#000000", "#f20505", "#ffffff", "#f0e046"],
    keywords: ["mickey mouse", "minnie mouse", "mouse", "cartoon"],
    name: "Mickey Mouse",
    id: "mickeymouse",
  },
  myntra: {
    colors: ["#F13AB1", "#E72744", "#FD913C", "#F05524", "#29303E"],
    keywords: ["myntra", "flipkart", "e-commerce"],
    name: "Myntra",
    id: "myntra",
  },
  nvidia: {
    colors: ["#FFFFFF", "#333333", "#000000", "#6AB900", "#76B900"],
    keywords: ["nvidia", "graphics"],
    name: "nVIDIA",
    id: "nvidia",
  },
  olive: {
    colors: ["#1C4015", "#54915F", "#9AD5D3"],
    keywords: ["olive", "fruit", "olive fruit"],
    name: "Olive",
    id: "olive",
  },
  oneplus: {
    colors: ["#F7FEFA", "#F60414"],
    keywords: ["oneplus", "one plus", "1+"],
    name: "OnePlus",
    id: "oneplus",
  },
  orange: {
    colors: ["#FFA809", "#FA7001", "#F8E9A4", "#F3CA10", "#6D9302"],
    keywords: ["orange", "fruit", "orange fruit"],
    name: "Orange",
    id: "orange",
  },
  paytm: {
    colors: ["#002E6E", "#00B9F1"],
    keywords: ["paytm", "pay tm", "online payment"],
    name: "Paytm",
    id: "paytm",
  },
  pear: {
    colors: ["#6F5930", "#A4B650", "#E7E453", "#D99D26", "#B14934"],
    keywords: ["pear", "fruit", "pear fruit"],
    name: "Pear",
    id: "pear",
  },
  pineapple: {
    colors: ["#7CB35C", "#557B3F", "#FFD964", "#C27815", "#A14712"],
    keywords: ["pineapple", "pine apple", "fruit", "pineapple fruit"],
    name: "Pineapple",
    id: "pineapple",
  },
  pinterest: {
    colors: ["#F0002A"],
    keywords: ["pinterest", "social network"],
    name: "Pinterest",
    id: "pinterest",
  },
  rainbow: {
    colors: [
      "#ee82ee",
      "#4b0082",
      "#0000ff",
      "#008000",
      "#ffff00",
      "#ffa500",
      "#ff0000",
    ],
    keywords: ["rainbow", "rainbow colors"],
    name: "Rainbow",
    id: "rainbow",
  },
  redsandalwood: {
    colors: ["#A45A52", "#DEA790", "#E3C4B0", "#DEB49C"],
    keywords: ["red sandal", "sandalwood", "wood", "tree"],
    name: "Red Sandalwood",
    id: "redsandalwood",
  },
  redwood: {
    colors: ["#431811", "#8F432B", "#ECB069", "#763C2C", "#B74B25"],
    keywords: ["redwood", "red wood", "wood", "tree"],
    name: "Redwood Finish Wood",
    id: "redwood",
  },
  samsung: {
    colors: ["#1428A0", "#2FB7E5", "#000000"],
    keywords: ["samsung", "sam sung"],
    name: "Samsung",
    id: "samsung",
  },
  sea: {
    colors: ["#E7F7EC", "#D4E8E9", "#A1CFFF", "#72D6EE", "#89BFFB", "#2DA0F9"],
    keywords: ["sea", "ocean", "river", "water"],
    name: "Sea",
    id: "sea",
  },
  shopify: {
    colors: ["#64943E", "#95BF47", "#FFFFFF", "#000000"],
    keywords: ["shopify", "shop"],
    name: "Shopify",
    id: "shopify",
  },
  standardwood: {
    colors: ["#DEB887", "#A55B53", "#5B270B"],
    keywords: ["standard", "wood", "tree"],
    name: "Standard Wood",
    id: "standardwood",
  },
  table: {
    colors: ["#D69E33", "#F6D756", "#E79126", "#784919", "#67390A"],
    keywords: ["table", "chair", "stool", "desk"],
    name: "Table",
    id: "table",
  },
  tree: {
    colors: ["#40EE95", "#0CAE5B", "#613B16", "#A67B51"],
    keywords: ["tree", "plant"],
    name: "Tree",
    id: "tree",
  },
  twitter: {
    colors: ["#326ada", "#d4d8d4", "#433e90", "#a19c9c", "#d2d2d2"],
    keywords: ["twitter", "social network"],
    name: "Twitter",
    id: "twitter",
  },
  whatsapp: {
    colors: ["#075E54", "#128C7E", "#25D366", "#DCF8C6", "#34B7F1", "#ECE5DD"],
    keywords: ["whatsapp", "whats app", "facebook", "messenger"],
    name: "WhatsApp",
    id: "whatsapp",
  },
  wordpress: {
    colors: ["#096484", "#4796B3", "#74B6CE", "#52ACCC"],
    keywords: ["wordpress", "word press"],
    name: "WordPress",
    id: "wordpress",
  },
};

export default palette;
